source('R/models.R')
source('R/validation.R')
source('R/discounts.R')
source('R/orders.R')
source('R/analytics.R')

stopifnot(validate_quantity(2))
stopifnot(!validate_quantity(0))
stopifnot(discount_rate(new_product('E','x','Electronics',1,1),10000)==0.05)
stopifnot(discount_rate(new_product('F','x','Fashion',1,1),3001)==0.10)
stopifnot(discount_rate(new_product('H','x','Home & Kitchen',1,1),1)==0.06)
stopifnot(discount_rate(new_product('B','x','Books & Stationery',1,1),100000)==0)

customers <- list(C1=new_customer('C1','Test','City'))
products <- list(P1=new_product('P1','Test Product','Electronics',1000,5))
orders <- list()
z <- place_order(customers,products,orders,'C1','P1',2,'UPI','2026-01-01')
stopifnot(z$products$P1$stock==3,length(z$orders)==1)
z2 <- cancel_order(z$products,z$orders,'O001')
stopifnot(z2$products$P1$stock==5,z2$orders$O001$status=='Cancelled')
d <- prepare_order_detail(customers,z2$products,z2$orders)
stopifnot(nrow(completed_orders(d))==0)
cat('All core tests passed.\n')
